<a href="https://colab.research.google.com/github/LIPPIE-LOUT/mpepeapi/blob/master/MorningAthletics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/datasets/world-athletics_all-time-top-lists.csv')

In [ ]:
df.head()

,all_time_rank,results_score,event,category,event_rank,mark,competitor,nat,date_of_birth,pos,...,venue,age,wind,mark_details,year_of_birth,event_name,event_type,environment,age_category,gender
0,1.0,1382.0,Women's Discus Throw,Outdoor Senior - Women,1,76.8,Gabriele REINSCH,GDR,1963-09-23,1.0,...,Neubrandenburg (GDR),24.8,NaN,NaN,1963.0,discus-throw,throws,outdoor,senior,women
1,2.0,1372.0,Women's Shot Put,Outdoor Senior - Women,1,22.63,Natalya LISOVSKAYA,URS,1962-07-16,1.0,...,Moskva (URS),24.9,NaN,NaN,1962.0,shot-put,throws,outdoor,senior,women
2,3.0,1371.0,Women's Shot Put,Outdoor Senior - Women,2,22.6,Natalya LISOVSKAYA,URS,1962-07-16,NaN,...,Moskva (URS),24.9,NaN,NaN,1962.0,shot-put,throws,outdoor,senior,women
3,4.0,1367.0,Women's Shot Put,Outdoor Senior - Women,3,22.55,Natalya LISOVSKAYA,URS,1962-07-16,1.0,...,Tallinn (EST),26.0,NaN,NaN,1962.0,shot-put,throws,outdoor,senior,women
4,5.0,1366.0,Women's Shot Put,Outdoor Senior - Women,4,22.53,Natalya LISOVSKAYA,URS,1962-07-16,1.0,...,Kiev (URS),26.1,NaN,NaN,1962.0,shot-put,throws,outdoor,senior,women

In [ ]:
df.shape

(488643, 21)

In [ ]:
df.duplicated().sum()

86

In [ ]:
df[df.duplicated()]

,all_time_rank,results_score,event,category,event_rank,mark,competitor,nat,date_of_birth,pos,...,venue,age,wind,mark_details,year_of_birth,event_name,event_type,environment,age_category,gender
5563,5488.0,1246.0,Men's Hammer Throw,Outdoor Senior - Men,117,82.78,Andrey ABDUVALIYEV,TJK,1966-06-30,1,...,Nitra (SVK),27.2,NaN,NaN,1966.0,hammer-throw,throws,outdoor,senior,men
9017,8966.0,1237.0,Men's Hammer Throw,Outdoor Senior - Men,220,82.24,Vyacheslav KOROVIN,URS,1962-09-08,1,...,Chelyabinsk (URS),24.8,NaN,NaN,1962.0,hammer-throw,throws,outdoor,senior,men
22209,22041.0,1218.0,Men's Hammer Throw,Outdoor Senior - Men,607,81.0,Tibor GÉCSEK,HUN,1964-09-22,1,...,Budapest (HUN),28.9,NaN,NaN,1964.0,hammer-throw,throws,outdoor,senior,men
23117,23052.0,1217.0,Men's Shot Put,Outdoor Senior - Men,758,21.61,Kevin AKINS,USA,1960-01-27,1,...,"Modesto, CA (USA)",23.3,NaN,NaN,1960.0,shot-put,throws,outdoor,senior,men
30387,28951.0,1212.0,Men's Hammer Throw,Outdoor Senior - Men,837,80.6,Heinz WEIS,FRG,1963-07-14,1,...,Berlin (GER),27.0,NaN,NaN,1963.0,hammer-throw,throws,outdoor,senior,men
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479383,NaN,1003.0,Men's 5km Road Race,Outdoor Senior - Men,1067,13:59,Mbongeni Amos NGXAZAZO,RSA,1980-02-02,1,...,Johannesburg (RSA),36.6,NaN,NaN,1980.0,5-kilometres,road-running,outdoor,senior,men
479438,NaN,1003.0,Men's 5km Road Race,Outdoor Senior - Men,1067,13:59,Nelson MOKORI,KEN,1992-07-22,1,...,"Des Moines, IA (USA)",21.8,NaN,NaN,1992.0,5-kilometres,road-running,outdoor,senior,men
479528,NaN,1003.0,Women's Hammer Throw,Outdoor U20 - Women,558,64.43,Anna BULGAKOVA,RUS,1988-01-17,1,...,"Adler, Sochi (RUS)",17.1,NaN,NaN,1988.0,hammer-throw,throws,outdoor,u20,women
479823,NaN,1000.0,Men's 5km Road Race,Outdoor Senior - Men,1141,14:00,Isaac HEYNE,AUS,2000-01-24,1,...,Adelaide (AUS),21.7,NaN,NaN,2000.0,5-kilometres,road-running,outdoor,senior,men
487984,NaN,NaN,Men's 60mH indoor (0.99),Indoor U20 - Men,150,7.75,Damion THOMAS,JAM,1999-06-29,1,...,"Winston Salem, NC (USA)",17.6,NaN,NaN,1999.0,60m-hurdles-990cm,hurdles,indoor,u20,men

In [ ]:
df = df.drop_duplicates()
df.duplicated().sum()

0

In [ ]:
df.duplicated(subset= "date_of_birth").sum()

472897

In [ ]:
len(df["event"].unique())

171

In [ ]:
df["event"].value_counts(normalize=True)

event
Women's Hammer Throw           0.026318
Women's 100m                   0.024724
Women's 200m                   0.024466
Women's 3000mSC                0.022908
Men's 100m                     0.022798
                                 ...
Women's 4x800m indoor          0.000059
Mixed 2x2x400m                 0.000055
Men's 4x800m indoor            0.000045
Women's Mile Road Race         0.000043
Mixed Shuttle Hurdles Relay    0.000027
Name: proportion, Length: 171, dtype: float64

In [ ]:
event_per_category = df.groupby("all_time_rank")["event_type"].sum().sort_values(ascending=False)
event_per_category.head()

all_time_rank
228162.0    throwsthrowsthrowsthrowsthrowsthrowsthrowsthro...
1994.0      throwsthrowsthrowsthrowsthrowsthrowsthrowsmidd...
101.0         throwsthrowsthrowsthrowsthrowsthrowsthrowsjumps
722.0       throwsthrowsthrowsthrowsthrowsthrowssprintsspr...
749.0       throwsthrowsthrowsthrowsthrowsthrowsjumpsthrow...
Name: event_type, dtype: object

In [ ]:
df[df["nat"] == "KEN"].head()

,all_time_rank,results_score,event,category,event_rank,mark,competitor,nat,date_of_birth,pos,...,venue,age,wind,mark_details,year_of_birth,event_name,event_type,environment,age_category,gender
139,140.0,1312.0,Men's Marathon,Outdoor Senior - Men,1,2:01:09,Eliud KIPCHOGE,KEN,1984-11-05,1,...,Berlin (GER),37.9,NaN,NaN,1984.0,marathon,road-running,outdoor,senior,men
151,150.0,1311.0,Men's 4x1500m,Outdoor Senior - Men,1,14:22.22,Kenya,KEN,NaN,1,...,"T. Robinson Stadium, Nassau (BAH)",NaN,NaN,NaN,NaN,4x1500-metres-relay,relays,outdoor,senior,men
196,188.0,1307.0,Men's Marathon,Outdoor Senior - Men,2,2:01:25,Kelvin KIPTUM,KEN,1999-12-02,1,...,London (GBR),23.4,NaN,NaN,1999.0,marathon,road-running,outdoor,senior,men
246,243.0,1303.0,Men's Marathon,Outdoor Senior - Men,3,2:01:39,Eliud KIPCHOGE,KEN,1984-11-05,1,...,Berlin (GER),33.9,NaN,NaN,1984.0,marathon,road-running,outdoor,senior,men
280,272.0,1301.0,Men's 800m,Outdoor Senior - Men,1,1:40.91,David RUDISHA,KEN,1988-12-17,1,...,"Olympic Stadium, London (GBR)",23.6,NaN,NaN,1988.0,800-metres,middle-long,outdoor,senior,men

In [ ]:
track = df[df["event_type"].isin(["middle-long", "sprints", "hurdles", "road-running", "race-walks", "relays"])]
track.head()

,all_time_rank,results_score,event,category,event_rank,mark,competitor,nat,date_of_birth,pos,...,venue,age,wind,mark_details,year_of_birth,event_name,event_type,environment,age_category,gender
12,13.0,1356.0,Men's 100m,Outdoor Senior - Men,1,9.58,Usain BOLT,JAM,1986-08-21,1,...,"Olympiastadion, Berlin (GER)",23.0,0.9,NaN,1986.0,100-metres,sprints,outdoor,senior,men
18,19.0,1352.0,Men's 200m,Outdoor Senior - Men,1,19.19,Usain BOLT,JAM,1986-08-21,1,...,"Olympiastadion, Berlin (GER)",23.0,-0.3,NaN,1986.0,200-metres,sprints,outdoor,senior,men
27,25.0,1341.0,Men's 400mH,Outdoor Senior - Men,1,45.94,Karsten WARHOLM,NOR,1996-02-28,1,...,"National Stadium, Tokyo (JPN)",25.4,NaN,NaN,1996.0,400-metres-hurdles,hurdles,outdoor,senior,men
28,29.0,1339.0,Men's 200m,Outdoor Senior - Men,2,19.26,Yohan BLAKE,JAM,1989-12-26,1,...,"Boudewijnstadion, Bruxelles (BEL)",21.7,0.7,NaN,1989.0,200-metres,sprints,outdoor,senior,men
32,30.0,1338.0,Men's 200m,Outdoor Senior - Men,3,19.3,Usain BOLT,JAM,1986-08-21,1,...,"National Stadium, Beijing (CHN)",22.0,-0.9,NaN,1986.0,200-metres,sprints,outdoor,senior,men

In [ ]:
df["event_type"].value_counts()

event_type
middle-long        117194
sprints             96488
jumps               84293
throws              76979
hurdles             54224
road-running        25105
race-walks          24621
relays               5596
combined-events      4057
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 488557 entries, 0 to 488642
Data columns (total 21 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   all_time_rank  365813 non-null  float64
 1   results_score  484649 non-null  float64
 2   event          488557 non-null  object
 3   category       488557 non-null  object
 4   event_rank     488557 non-null  int64
 5   mark           488557 non-null  object
 6   competitor     488557 non-null  object
 7   nat            488557 non-null  object
 8   date_of_birth  477196 non-null  object
 9   pos            485322 non-null  object
 10  date           488557 non-null  object
 11  venue          488557 non-null  object
 12  age            477196 non-null  float64
 13  wind           81393 non-null   float64
 14  mark_details   11239 non-null   object
 15  year_of_birth  480369 non-null  float64
 16  event_name     488557 non-null  object
 17  event_type     488557 non-null  object
 18  environment    488557 non-null  object
 19  age_category   488557 non-null  object
 20  gender         488557 non-null  object
dtypes: float64(5), int64(1), object(15)
memory usage: 82.0+ MB

In [ ]:
unique_